#!/bin/sh -eu
if [ -z "${REACT_APP_API_URL:-}" ]; then
    API_URL=undefined
else
    API_URL=${REACT_APP_API_URL}
fi
if [ -z "${REACT_APP_USERS_URL:-}" ]; then
    APP_USERS_URL=undefined
else
    APP_USERS_URL=${REACT_APP_USERS_URL}
fi
if [ -z "${REACT_APP_CELERY_FLOWR_API_URL:-}" ]; then
    APP_CELERY_FLOWR_API_URL=undefined
else
    APP_CELERY_FLOWR_API_URL=${REACT_APP_CELERY_FLOWR_API_URL}
fi
VERSION=$( cat VERSION )
cat <<EOF
window.REACT_APP_API_URL='$API_URL'
window.REACT_APP_USERS_URL='$APP_USERS_URL'
window.REACT_APP_CELERY_FLOWR_API_URL='$APP_CELERY_FLOWR_API_URL'
window.VERSION='$VERSION'
EOF